import { type GetServerSidePropsContext } from "next";
import Head from "next/head";
import Nav from "~/components/Common/Nav";
import { api } from "~/utils/api";

import { requireAuth } from "~/utils/requireAuth";

export default function Profile() {
  const myUser = api.user.getUser.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Nav user={myUser.data} />

        <div className="h-36"></div>

        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Profile
        </h1>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  // const needsSetup = await checkRequireSetup(context);
  const loggedIn = await requireAuth(context);

  if (!loggedIn) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
